# Generated by Django 4.0.5 on 2022-06-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_iscorrect_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='Note',
        ),
    ]
