# Generated by Django 4.0.5 on 2022-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_notes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asktext',
            field=models.TextField(),
        ),
    ]
